hot swap C2 with Pneuma
preludeorg/pneuma pull request #21
Opened 2021-01-14 00:18 UTC by khyberspache

2021-01-14 11:59 UTC, privateducky requested changes
This isn't bad ;) but it is too complex still. I want to keep iterating on this a little bit. I don't want to give too much direction w/out diving into the code myself, but the code complexity seems to be coming out of ResetFlag existing.

2021-01-15 13:55 UTC, privateducky requested changes
Ok, had some time to jump in to this code this a.m. I think this implementation is a bit too complex. I see 2 decent alternatives, which should work well:

1. In the 2 places we call "SetAgentConfig()" run a go-routine for "CommunicationChannels[agent.Contact].Communicate()" and then end the calling process. This will need some shuffling around to ensure no circular dependencies.
2. In main.go, kick off a go-routine for all protocols simultaneously. Then have each keep tabs (every minute?) to see if it is active. Only the active one would be in its "normal" loop. To do this, it'd be easiest to remove the go routine in the tcp/udp contacts (respond() functions) because you could then easily manage the state of the process.

I'm happy to spin up a POC around either of these but wanted to give you my thoughts first.

2021-01-15 14:28 UTC, khyberspache commented
We should go w/ 1, because we don't want 4 C2 channels beaconing simultaneously for so many reasons lol

2021-01-15 14:34 UTC, khyberspache commented
Misunderstood, but we would need channel magic to pass beacons between the go routines which would bloat the code

2021-01-15 18:32 UTC, khyberspache commented
Closing for https://github.com/preludeorg/pneuma/pull/25

2021-01-15 18:32 UTC, closed without merging