handle payload download errors gracefully
preludeorg/pneuma pull request #47
Opened 2021-02-05 16:46 UTC by khyberspache

2021-02-05 22:25 UTC, privateducky commented on sockets/contact.go
> +	link.Status = -1
why -1 and not a 1 in general to indicate not worked?

2021-02-05 22:26 UTC, privateducky commented on sockets/rawgrpc.go
>  				if len(link.Payload) > 0 {
this payload block/sequence is too duplicate across the sockets. can we move to the contact.go (base) instead?

2021-02-05 22:27 UTC, privateducky requested changes
questions

2021-02-08 00:02 UTC, khyberspache commented on sockets/rawgrpc.go
>  				if len(link.Payload) > 0 {
did a little bit of reducing, but I don't want to do too much more

2021-02-08 20:52 UTC, privateducky approved these changes

2021-02-08 20:52 UTC, merged